services:
    speedtest-tracker:
        image: lscr.io/linuxserver/speedtest-tracker:latest
        container_name: speedtest-tracker
        ports:
            - 8081:80
            - 8443:443
        environment:
            - PUID=1000
            - PGID=1000
            - APP_KEY=base64:tcqdKpinit9UqsvoDzFkcPyFIlgO1pdajWnx9SdRyyo=
            - APP_URL=http://localhost
            - DB_CONNECTION=sqlite
            - APP_TIMEZONE=America/Toronto
            - SPEEDTEST_SCHEDULE= 6 */2 * * *
        volumes:
            - /mnt/data/speedtest_tacker/config:/config
            - /mnt/data/speedtest_tacker/ssl-keys/:/config/keys
        restart: unless-stopped