services:
  web:
    image: registry.gitlab.com/storyteller-platform/storyteller:latest
    container_name: storyteller
    restart: unless-stopped
    volumes:
      # Remplacer ~/ par le chemin absolu vers le dossier de données de l'utilisateur
      - /mnt/data/storyteller/data:/data:rw
    environment:
      - STORYTELLER_SECRET_KEY_FILE=/run/secrets/secret_key
      - USE_GPU=false
    ports:
      - "8001:8001"
    secrets:
      - secret_key
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - driver: nvidia
    #          count: all
    #          capabilities: [gpu]
secrets:
  secret_key:
    # Chemin absolu vers le fichier texte contenant la clé secrète sur le serveur
    file: /mnt/data/storyteller/STORYTELLER_SECRET_KEY.txt
